// automatically generated by the FlatBuffers compiler, do not modify

package flats

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FrameData struct {
	_tab flatbuffers.Table
}

func GetRootAsFrameData(buf []byte, offset flatbuffers.UOffsetT) *FrameData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FrameData{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FrameData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FrameData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FrameData) FrameId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FrameData) MutateFrameId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *FrameData) OperationList(obj *Operation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FrameData) OperationListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FrameDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FrameDataAddFrameId(builder *flatbuffers.Builder, frameId uint32) {
	builder.PrependUint32Slot(0, frameId, 0)
}
func FrameDataAddOperationList(builder *flatbuffers.Builder, operationList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(operationList), 0)
}
func FrameDataStartOperationListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FrameDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
