// automatically generated by the FlatBuffers compiler, do not modify

package flats

const (
	OpTypeMove = 1
	OpTypeShoot = 2
)

var EnumNamesOpType = map[int]string{
	OpTypeMove:"Move",
	OpTypeShoot:"Shoot",
}

