// automatically generated by the FlatBuffers compiler, do not modify

package flats

const (
	PacketIdNone = 0
	PacketIdHeartBeat = 1
	PacketIdLogin = 2
	PacketIdGame = 5
)

var EnumNamesPacketId = map[int]string{
	PacketIdNone:"None",
	PacketIdHeartBeat:"HeartBeat",
	PacketIdLogin:"Login",
	PacketIdGame:"Game",
}

