// automatically generated by the FlatBuffers compiler, do not modify

package flats

const (
	RequestIdNone = 0
	RequestIdLogin = 10
)

var EnumNamesRequestId = map[int]string{
	RequestIdNone:"None",
	RequestIdLogin:"Login",
}

