// automatically generated by the FlatBuffers compiler, do not modify

package flats

const (
	ResponseIdNone = 0
	ResponseIdLogin = 10
	ResponseIdJoinRoom = 11
	ResponseIdMySpawnData = 12
)

var EnumNamesResponseId = map[int]string{
	ResponseIdNone:"None",
	ResponseIdLogin:"Login",
	ResponseIdJoinRoom:"JoinRoom",
	ResponseIdMySpawnData:"MySpawnData",
}

