// automatically generated by the FlatBuffers compiler, do not modify

package flats

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpAllPlayerSpawns struct {
	_tab flatbuffers.Table
}

func GetRootAsRpAllPlayerSpawns(buf []byte, offset flatbuffers.UOffsetT) *RpAllPlayerSpawns {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpAllPlayerSpawns{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RpAllPlayerSpawns) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpAllPlayerSpawns) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpAllPlayerSpawns) Pid() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpAllPlayerSpawns) MutatePid(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *RpAllPlayerSpawns) Others(obj *RpPlayerSpawn, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RpAllPlayerSpawns) OthersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RpAllPlayerSpawnsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RpAllPlayerSpawnsAddPid(builder *flatbuffers.Builder, pid byte) {
	builder.PrependByteSlot(0, pid, 0)
}
func RpAllPlayerSpawnsAddOthers(builder *flatbuffers.Builder, others flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(others), 0)
}
func RpAllPlayerSpawnsStartOthersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RpAllPlayerSpawnsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
