// automatically generated by the FlatBuffers compiler, do not modify

package flats

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpLogin struct {
	_tab flatbuffers.Table
}

func GetRootAsRpLogin(buf []byte, offset flatbuffers.UOffsetT) *RpLogin {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpLogin{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RpLogin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpLogin) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpLogin) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RpLoginStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RpLoginAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func RpLoginEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
