// automatically generated by the FlatBuffers compiler, do not modify

package flats

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpPlayerSceneData struct {
	_tab flatbuffers.Table
}

func GetRootAsRpPlayerSceneData(buf []byte, offset flatbuffers.UOffsetT) *RpPlayerSceneData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpPlayerSceneData{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RpPlayerSceneData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpPlayerSceneData) Table() flatbuffers.Table {
	return rcv._tab
}

func RpPlayerSceneDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RpPlayerSceneDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
