// automatically generated by the FlatBuffers compiler, do not modify

package flats

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RqLogin struct {
	_tab flatbuffers.Table
}

func GetRootAsRqLogin(buf []byte, offset flatbuffers.UOffsetT) *RqLogin {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RqLogin{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RqLogin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RqLogin) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RqLogin) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RqLogin) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RqLoginStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RqLoginAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func RqLoginAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(password), 0)
}
func RqLoginEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
